GRANT SELECT ON CLIFOR TO rotas;
GRANT SELECT ON CIDADE TO rotas;
GRANT SELECT ON VEICULO TO rotas;
GRANT SELECT ON ITEM TO rotas;
GRANT SELECT ON LOCACAO_PRODUTO TO rotas;
GRANT SELECT ON ENTREGA_PCAB TO rotas;
GRANT SELECT ON ENTREGA_CAB TO rotas;
